server:
  port: 8013

spring:
  application:
    name: x-server
  sleuth:
    #baggage-keys:   # 注意, Sleuth2.0.0之后, baggage的 key 必须在这里配置才能生效
    #  - SessionId
    web:
      client:
        enabled: true #是否开启
    sampler:
      probability: ${ZIPKIN_RATE:0.1}
  zipkin:
    base-url: http://x.x.x.x:9411/
    sender:
      type: web
  bus:
    trace:
      enabled: true # 开启消息总线 & bus-refresh 端口
    enabled: true
  boot:
    admin:
      client:
        url: http://x.x.x.x:8012
        username: x
        password: x
        instance:
          service-url: http://${spring.cloud.client.ip-address}:${server.port}
          prefer-ip: true    
  rabbitmq:
    host: x.x.x.x
    port: 5672
    username: x
    password: x
management:
  health:
    db:
      enabled: false
    mail:
      enabled: false
    redis:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有节点 "bus-refresh"
    health:
      senysssitive: false #关闭过滤敏感信息
  endpoint:
    health:
      show-details: ALWAYS #显示详细信息
turbine:
  appConfig: config-server,uc-server,scheduler-server,cmdb-server,workflow-server,fc-server,troublereport-server,devops-server
  clusterNameExpression: new String("default")
  #turbine:
  #  app-config: config-service,gateway-service,authorization-service
  #  aggregator:
  #    clusterConfig: default
  #  clusterNameExpression: "'default'"
  #  combine-host: true
  #  instanceUrlSuffix: actuator/hystrix.stream
  # default: actuator/hystrix.stream #key是clusterConfig集群的名字，value是hystrix监控的后缀，springboot2.0为actuator/hystrix.stream
