(function(){var h;function p(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var aa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=aa.exec(a);){var d=p(c[1],c[1]),e=c[2]?p(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var r="";
function t(a){var b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{var d=self.AMP_CONFIG||{};c=q(b.location.originalHash||b.location.hash);d=d.spt;var e=q(b.location.search);r||(r=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012005262159000");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(c.development)||b.AMP_DEV_MODE),examiner:"2"==c.development,esm:!1,geoOverride:c["amp-geo"],minified:!0,lite:void 0!=e.amp_lite,test:!1,log:c.log,version:"2005262159000",rtvVersion:r,
singlePassType:d};c=b.__AMP_MODE=c}return c};function ba(a){var b=!1,c=null,d=a;return function(a){for(var e=[],g=0;g<arguments.length;++g)e[g-0]=arguments[g];b||(c=d.apply(self,e),b=!0,d=null);return c}};var v=self.AMP_CONFIG||{},w=("string"==typeof v.cdnProxyRegex?new RegExp(v.cdnProxyRegex):v.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function x(a){if(!self.document||!self.document.head||self.location&&w.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var y={thirdParty:v.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:v.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof v.thirdPartyFrameRegex?new RegExp(v.thirdPartyFrameRegex):v.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:v.cdnUrl||x("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:w,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:v.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:v.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:v.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:v.geoApiUrl||x("amp-geo-api")};function ca(){}function da(a,b){return b.reduce(function(a,b){return a+"&s[]="+encodeURIComponent(String(z(b)))},"https://log.amp.dev/?v=012005262159000&id="+encodeURIComponent(a))}
function A(a,b,c){var d=this;c=void 0===c?"":c;this.win=a;this.Y=b;this.w=this.win.console&&this.win.console.log&&"0"!=t().log?this.Y(parseInt(t().log,10),t().development):0;this.H=c;this.D=null;this.U=ba(function(){a.fetch(y.cdn+"/rtv/012005262159000/log-messages.simple.json").then(function(a){return a.json()},ca).then(function(a){a&&(d.D=a)})})}
function B(a,b,c,d){if(0!=a.w){var e=a.win.console.log;"ERROR"==c?e=a.win.console.error||e:"INFO"==c?e=a.win.console.info||e:"WARN"==c&&(e=a.win.console.warn||e);c=Array.isArray(d[0])?ea(a,d[0]):d;b="["+b+"]";"string"===typeof c[0]?c[0]=b+" "+c[0]:c.unshift(b);e.apply(a.win.console,c)}}h=A.prototype;h.isEnabled=function(){return 0!=this.w};h.fine=function(a,b){4<=this.w&&B(this,a,"FINE",Array.prototype.slice.call(arguments,1))};
h.info=function(a,b){3<=this.w&&B(this,a,"INFO",Array.prototype.slice.call(arguments,1))};h.warn=function(a,b){2<=this.w&&B(this,a,"WARN",Array.prototype.slice.call(arguments,1))};h.P=function(a,b){if(1<=this.w)B(this,a,"ERROR",Array.prototype.slice.call(arguments,1));else{var c=C.apply(null,Array.prototype.slice.call(arguments,1));D(this,c);return c}};h.error=function(a,b){var c=this.P.apply(this,arguments);c&&(c.name=a||c.name,self.__AMP_REPORT_ERROR(c))};
h.expectedError=function(a,b){var c=this.P.apply(this,arguments);c&&(c.expected=!0,self.__AMP_REPORT_ERROR(c))};h.createError=function(a){var b=C.apply(null,arguments);D(this,b);return b};h.createExpectedError=function(a){var b=C.apply(null,arguments);D(this,b);b.expected=!0;return b};
h.assert=function(a,b,c){var d;if(Array.isArray(b))return this.assert.apply(this,[a].concat(ea(this,b)));if(!a){var e=(b||"Assertion failed").split("%s"),f=e.shift(),g=f,l=[],k=2;for(""!=f&&l.push(f);0<e.length;){var m=e.shift(),n=arguments[k++];n&&n.tagName&&(d=n);l.push(n);f=m.trim();""!=f&&l.push(f);g+=z(n)+m}k=Error(g);k.fromAssert=!0;k.associatedElement=d;k.messageArray=l;D(this,k);self.__AMP_REPORT_ERROR(k);throw k;}return a};
h.assertElement=function(a,b){E(this,a,a&&1==a.nodeType,"Element expected",b);return a};h.assertString=function(a,b){E(this,a,"string"==typeof a,"String expected",b);return a};h.assertNumber=function(a,b){E(this,a,"number"==typeof a,"Number expected",b);return a};h.assertArray=function(a,b){E(this,a,Array.isArray(a),"Array expected",b);return a};h.assertBoolean=function(a,b){E(this,a,!!a===a,"Boolean expected",b);return a};
h.assertEnumValue=function(a,b,c){a:{for(var d in a)if(a[d]===b){a=!0;break a}a=!1}if(a)return b;this.assert(!1,'Unknown %s value: "%s"',c||"enum",b)};function D(a,b){b=F(b);a.H?b.message?-1==b.message.indexOf(a.H)&&(b.message+=a.H):b.message=a.H:0<=b.message.indexOf("\u200b\u200b\u200b")&&(b.message=b.message.replace("\u200b\u200b\u200b",""))}function ea(a,b){var c=b.shift();t(a.win).development&&a.U();return a.D&&c in a.D?[a.D[c]].concat(b):["More info at "+da(c,b)]}
function E(a,b,c,d,e){Array.isArray(e)?a.assert(c,e.concat(b)):a.assert(c,(e||d)+": %s",b)}function z(a){return a&&1==a.nodeType?a.tagName.toLowerCase()+(a.id?"#"+a.id:""):a}function F(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}
function C(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=F(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var G=self.__AMP_LOG,H=null;function fa(){G.user||(G.user=ha());return G.user}function ha(){if(!H)throw Error("failed to call initLogConstructor");return new H(self,function(a,b){return b||1<=a?4:2},"\u200b\u200b\u200b")}
function I(){if(G.dev)return G.dev;if(!H)throw Error("failed to call initLogConstructor");return G.dev=new H(self,function(a){return 3<=a?4:2<=a?3:0})};function J(a){return a||{}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function K(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function L(a,b,c){c=void 0===c?{}:c;var d=void 0===d?null:d;c.type=a;c.sentinel=b;return"amp-"+(d||"")+JSON.stringify(c)};function M(){this.S=100;this.K=this.O=0;this.A=Object.create(null)}M.prototype.has=function(a){return!!this.A[a]};M.prototype.get=function(a){var b=this.A[a];if(b)return b.access=++this.K,b.payload};M.prototype.put=function(a,b){this.has(a)||this.O++;this.A[a]={payload:b,access:this.K};if(!(this.O<=this.S)){I().warn("lru-cache","Trimming LRU cache");a=this.A;var c=this.K+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.O--)}};J({c:!0,v:!0,a:!0,ad:!0,action:!0});var N,ia;var O,ja="Webkit webkit Moz moz ms O o".split(" ");function ka(a,b,c){if(K(b,"--"))return b;O||(O=Object.create(null));var d=O[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<ja.length;f++){var g=ja[f]+e;if(void 0!==a[g]){e=g;break a}}e=""}var l=e;void 0!==a[l]&&(d=l)}c||(O[b]=d)}return d}function la(a){var b={"pointer-events":"none"};a=a.style;for(var c in b)a.setProperty(ka(a,c),b[c].toString(),"important")}
function ma(a,b,c){(b=ka(a.style,b,void 0))&&(K(b,"--")?a.style.setProperty(b,c):a.style[b]=c)}function P(a,b){for(var c in b)ma(a,c,b[c])}function na(a,b){for(var c=0;c<b.length;c++)ma(a,b[c],null)};function oa(a){try{return!!a.location.href&&(a.test||!0)}catch(b){return!1}};function Q(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c,x:a,y:b}}function R(a){return Q(Number(a.left),Number(a.top),Number(a.width),Number(a.height))};function pa(a,b,c){var d=b.top+"px",e=c.width-(b.left+b.width)+"px",f=b.left+"px",g=c.height-(b.top+b.height)+"px",l=b.height+"px",k=b.width+"px";var m=c.width/2-b.width/2-b.left+"px";var n=c.height/2-b.height/2-b.top+"px";"number"==typeof m&&(m+="px");void 0===n?m="translate("+m+")":("number"==typeof n&&(n+="px"),m="translate("+m+", "+n+")");P(a,{position:"fixed",top:d,right:e,left:f,bottom:g,height:l,width:k,transition:"transform 150ms ease",transform:m,margin:0})};function S(a,b,c){a.requestAnimationFrame(function(){b.measure&&b.measure(c);b.mutate&&b.mutate(c)})};function ua(a,b,c){S(a,{measure:function(c){c.viewportSize={width:a.innerWidth,height:a.innerHeight};c.rect=R(b.getBoundingClientRect())},mutate:function(d){var e=d.viewportSize,f=Q(0,0,e.width,e.height);pa(b,d.rect,d.viewportSize);la(b);setTimeout(function(){S(a,{mutate:function(){na(b,["pointer-events"]);P(b,{position:"fixed","z-index":1E3,left:0,right:0,top:0,bottom:0,width:"100vw",height:"100vh",transition:null,transform:null,margin:0,border:0});c(d.rect,f)}})},200)}},{})}
function va(a,b,c,d){S(a,{mutate:function(){na(b,"position z-index left right top bottom width height margin border".split(" "));c();S(a,{measure:function(){d(R(b.getBoundingClientRect()))}})}})};function T(a){this.o=a;this.I=this.L=!1;this.B=null;wa(this)}function wa(a){a.o.addEventListener("resize",function(){return a.onWindowResize()})}T.prototype.onWindowResize=function(){this.L&&(this.I=!0)};T.prototype.expandFrame=function(a,b){var c=this;ua(this.o,a,function(a,e){c.L=!0;c.I=!1;c.B=a;b(e)})};T.prototype.collapseFrame=function(a,b){var c=this;va(this.o,a,function(){c.L=!1;c.I||b(c.B)},function(a){c.B=a;c.I&&b(c.B)})};function xa(){this.h=null}h=xa.prototype;h.add=function(a){var b=this;this.h||(this.h=[]);this.h.push(a);return function(){b.remove(a)}};h.remove=function(a){this.h&&(a=this.h.indexOf(a),-1<a&&this.h.splice(a,1))};h.removeAll=function(){this.h&&(this.h.length=0)};h.fire=function(a){if(this.h)for(var b=this.h,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.h?this.h.length:0};function ya(a,b){function c(c){f=null;e=a.setTimeout(d,100);b.apply(null,c)}function d(){e=0;f&&c(f)}var e=0,f=null;return function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];e?f=b:c(b)}};function U(a){this.o=a;this.G=null;var b=this.o;a=b.document;if(a.scrollingElement)a=a.scrollingElement;else{var c;if(c=a.body)b=b.navigator.userAgent,c=/WebKit/i.test(b)&&!/Edge/i.test(b);a=c?a.body:a.documentElement}this.Z=a;this.J=null}
U.prototype.observe=function(a,b){var c=this;if(!this.G){this.G=new xa;var d=ya(this.o,function(){c.J=c.getViewportRect();c.G.fire()});this.J=this.getViewportRect();this.o.addEventListener("scroll",d,!0);this.o.addEventListener("resize",d,!0)}b({viewportRect:this.J,targetRect:this.getTargetRect(a)});return this.G.add(function(){b({viewportRect:c.J,targetRect:c.getTargetRect(a)})})};
U.prototype.getViewportRect=function(){var a=this.Z,b=this.o;return Q(Math.round(a.scrollLeft||b.pageXOffset),Math.round(a.scrollTop||b.pageYOffset),b.innerWidth,b.innerHeight)};U.prototype.getTargetRect=function(a){for(var b=R(a.getBoundingClientRect()),c=0,d=a.ownerDocument.defaultView;10>c&&d&&d!=this.o&&d!=this.o.top;c++,d=d.parent){var e=R(d.frameElement.getBoundingClientRect());a=b;var f=e.left,g=e.top;b=0==f&&0==g||0==a.width&&0==a.height?a:Q(a.left+f,a.top+g,a.width,a.height)}return b};var za=["send-positions"];function V(){this.M={}}V.prototype.listen=function(a,b){this.M[a]=b};V.prototype.fire=function(a,b,c){return a in this.M?this.M[a].apply(b,c):!1};
function Aa(a,b){var c=oa(a.top)?a.top:a;this.C=b;this.j=Object.create(null);c.ampInaboxPositionObserver=c.ampInaboxPositionObserver||new U(c);this.N=c.ampInaboxPositionObserver;this.F=new V;c.ampInaboxFrameOverlayManager=c.ampInaboxFrameOverlayManager||new T(c);this.R=c.ampInaboxFrameOverlayManager;this.F.listen("send-positions",this.X);this.F.listen("full-overlay-frame",this.W);this.F.listen("cancel-full-overlay-frame",this.V)}h=Aa.prototype;
h.processMessage=function(a){var b=a.data;if("string"==typeof b&&0==b.indexOf("amp-")&&-1!=b.indexOf("{")){var c=b.indexOf("{");try{var d=JSON.parse(b.substr(c))}catch(u){I().error("MESSAGING","Failed to parse message: "+b,u),d=null}}else d=null;if(!d||!d.sentinel)return!1;a:if(b=d.sentinel,this.j[b])b=this.j[b];else{if(c=this.getMeasureableFrame(a.source))for(var e=c.contentWindow,f=0;f<this.C.length;f++)for(var g=this.C[f],l=0,k=e;10>l;l++,k=k.parent){if(g.contentWindow==k){this.j[b]={iframe:g,
measurableFrame:c};b=this.j[b];break a}if(k==window.top)break}b=null}var m=b;if(!m)return I().info("InaboxMessagingHost","Ignored message from untrusted iframe:",a),!1;var n=m.iframe.dataset.ampAllowed;return-1===(n?n.split(/\s*,\s*/):za).indexOf(d.type)?(I().info("InaboxMessagingHost","Ignored non-whitelisted message type:",a),!1):this.F.fire(d.type,this,[m.measurableFrame,d,a.source,a.origin])?!0:(I().warn("InaboxMessagingHost","Unprocessed AMP message:",a),!1)};
h.X=function(a,b,c){var d=this.N.getViewportRect(),e=this.N.getTargetRect(a);Ba(b,c,J({viewportRect:d,targetRect:e}));this.j[b.sentinel].observeUnregisterFn=this.j[b.sentinel].observeUnregisterFn||this.N.observe(a,function(a){return Ba(b,c,a)});return!0};function Ba(a,b,c){b.postMessage(L("position",a.sentinel,c),"*")}h.W=function(a,b,c,d){this.R.expandFrame(a,function(a){c.postMessage(L("full-overlay-frame-response",b.sentinel,J({success:!0,boxRect:a})),d)});return!0};
h.V=function(a,b,c,d){this.R.collapseFrame(a,function(a){c.postMessage(L("cancel-full-overlay-frame-response",b.sentinel,J({success:!0,boxRect:a})),d)});return!0};h.getMeasureableFrame=function(a){if(!a)return null;for(var b,c=0,d=a;10>c&&d!=d.top&&!oa(d);c++,b=d,d=d.parent);if(b){c=b.parent.document.querySelectorAll("iframe");d=0;for(var e=c[d];d<c.length;d++,e=c[d])if(e.contentWindow==b)return e}return a.frameElement};
h.unregisterIframe=function(a){var b=this.C.indexOf(a);-1!=b&&this.C.splice(b,1);for(var c in this.j)this.j[c].iframe==a&&(this.j[c].observeUnregisterFn&&this.j[c].observeUnregisterFn(),delete this.j[c])};var W;function Ca(a){a=a.__AMP_TOP||(a.__AMP_TOP=a);return Da(a,"ampdoc")}function Ea(a){var b=Fa(a);b=Fa(b);b=b.isSingleDoc()?b.win:b;return Da(b,"viewer")}function Fa(a){return a.nodeType?Ca((a.ownerDocument||a).defaultView).getAmpDoc(a):a}function Da(a,b){var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};function Ga(){var a=Ha();return function(b){return setTimeout(b,a())}}function Ha(){var a=0;return function(){var b=Math.pow(1.5,a++);var c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var Ia=!1;function Ja(a){Ia||(Ia=!0,P(a.body,{opacity:1,visibility:"visible",animation:"none"}))};var X=self.__AMP_ERRORS||[];self.__AMP_ERRORS=X;function Y(a){Y=Ga();return Y(a)}function Ka(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var Z;
function La(a,b){try{if(a)if(void 0!==a.message)a=F(a);else{var c=a;a=Error(Ka(c));a.origError=c}else a=Error("Unknown error");if(a.reported)return a;a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),t().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?e.call(console,a.message,d):e.call(console,a.message)}d&&
d.T&&d.T("amp:error",a.message);Ma.call(void 0,void 0,void 0,void 0,void 0,a)}catch(f){setTimeout(function(){throw f;})}return a}function Ma(a,b,c,d,e){var f=this;this&&this.document&&Ja(this.document);if(!t().development){var g=!1;try{g=Na()}catch(k){}if(!(g&&.01<Math.random())){var l=Oa(a,b,c,d,e,g);l&&Y(function(){try{return Pa(f,l).catch(function(){})}catch(k){}})}}}
function Pa(a,b){b.pt&&.9>Math.random()?(W||(W=Promise.resolve(void 0)),a=W):a=Qa(a,b).then(function(a){if(!a){var c=new XMLHttpRequest;c.open("POST",.1>Math.random()?y.betaErrorReporting:y.errorReporting,!0);c.send(JSON.stringify(b))}});return a}
function Qa(a,b){var c=Ca(a);if(!c.isSingleDoc())return Promise.resolve(!1);var d=c.getSingleDoc();if(!d.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var e=Ea(d);return e.hasCapability("errorReporter")?e.isTrustedViewer().then(function(a){if(!a)return!1;e.sendMessage("error",J({m:b.m,a:b.a,s:b.s,el:b.el,ex:b.ex,v:b.v,pt:b.pt,jse:b.jse}));return!0}):Promise.resolve(!1)}
function Oa(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var l=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var k=!(self&&self.window),m=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||k)if(l=!0,.001<m)return;var n=0<=a.indexOf("\u200b\u200b\u200b");if(!(n&&.1<m)){g=Object.create(null);g.v=t().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=n?"1":"0";g.ex=l?"1":"0";g.dw=k?"1":"0";var u="1p";self.context&&
self.context.location?(g["3p"]="1",u="3p"):t().runtime&&(u=t().runtime);t().singlePassType&&(g.spt=t().singlePassType);g.rt=u;"inabox"===u&&(g.adid=t().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var qa=
self.AMP.viewer.getResolvedViewerUrl(),ra=self.AMP.viewer.maybeGetMessagingOrigin();qa&&(g.rvu=qa);ra&&(g.mso=ra)}Z||(Z=Ra());g.jse=Z;var sa=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var ta in f)sa.push(ta+"="+(f[ta]?"1":"0"));g.exps=sa.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),n||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document?self.document.referrer:
"";g.ae=X.join(",");g.fr=self.location.originalHash||self.location.hash;"production"===g.bt&&(g.pt="1");b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return g}}}
function Na(){var a=self;if(!a.document)return!1;a=a.document.querySelectorAll("script[src]");for(var b=0;b<a.length;b++){var c=a[b].src.toLowerCase();if("string"==typeof c){N||(N=self.document.createElement("a"),ia=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new M));var d=ia,e=N;if(d&&d.has(c))c=d.get(c);else{e.href=c;e.protocol||(e.href=e.href);var f={href:e.href,protocol:e.protocol,host:e.host,hostname:e.hostname,port:"0"==e.port?"":e.port,pathname:e.pathname,search:e.search,hash:e.hash,origin:null};
"/"!==f.pathname[0]&&(f.pathname="/"+f.pathname);if("http:"==f.protocol&&80==f.port||"https:"==f.protocol&&443==f.port)f.port="",f.host=f.hostname;f.origin=e.origin&&"null"!=e.origin?e.origin:"data:"!=f.protocol&&f.host?f.protocol+"//"+f.host:f.href;d&&d.put(c,f);c=f}}if(!y.cdnProxyRegex.test(c.origin))return!0}return!1}
function Ra(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(K(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(K(b,"Error: message"))return"Chrome"}return"unknown"};new function(a){if(a.ampInaboxInitialized)I().info("inabox-host","Skip a 2nd attempt of initializing AMP inabox host.");else{a.ampInaboxInitialized=!0;H=A;I();fa();self.__AMP_REPORT_ERROR=La;a.ampInaboxIframes&&!Array.isArray(a.ampInaboxIframes)&&(I().info("inabox-host","Invalid %s. %s","ampInaboxIframes",a.ampInaboxIframes),a.ampInaboxIframes=[]);var b=new Aa(a,a.ampInaboxIframes);a.AMP=a.AMP||{};a.AMP.inaboxUnregisterIframe?I().info("inabox-host","win.AMP[inaboxUnregisterIframe] already defined}"):
a.AMP.inaboxUnregisterIframe=b.unregisterIframe.bind(b);var c=a.ampInaboxPendingMessages,d=function(a){try{b.processMessage(a)}catch(f){I().error("inabox-host","Error processing inabox message",a,f)}};c&&(Array.isArray(c)?c.forEach(function(a){var b=!(!a.source||!a.source.postMessage);b||fa().warn("inabox-host","Ignoring an inabox message. Likely the requester iframe has been removed. message.data="+JSON.stringify(a.data));b&&d(a)}):I().info("inabox-host","Invalid %s %s","ampInaboxPendingMessages",
c));a.ampInaboxPendingMessages=[];a.ampInaboxPendingMessages.push=function(){};a.addEventListener("message",d.bind(b))}}(self);})();

//# sourceMappingURL=amp4ads-host-v0.js.map
